// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back.Data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("back.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("back.Models.Grades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("aproved")
                        .HasColumnType("INTEGER");

                    b.Property<double>("av1")
                        .HasColumnType("REAL");

                    b.Property<double>("av2")
                        .HasColumnType("REAL");

                    b.Property<double>("av3")
                        .HasColumnType("REAL");

                    b.Property<double>("avf")
                        .HasColumnType("REAL");

                    b.Property<bool>("final")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idstudent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idsubject")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("grades");
                });

            modelBuilder.Entity("back.Models.Prof", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("back.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("aproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idclass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("back.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idprof")
                        .HasColumnType("INTEGER");

                    b.Property<double>("w1")
                        .HasColumnType("REAL");

                    b.Property<double>("w2")
                        .HasColumnType("REAL");

                    b.Property<double>("w3")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
